# Generated by Django 5.2.3 on 2025-08-17 19:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen_base64', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('GERENTE', 'Gerente'), ('JEFE', 'Jefe'), ('TECNICO', 'Técnico')], max_length=20)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiculos.empresa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_orden', models.PositiveIntegerField(editable=False, null=True, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(default='Sin modelo', max_length=100)),
                ('color', models.CharField(default='Sin color', max_length=50)),
                ('tipo_bencina', models.CharField(default='Sin especificar', max_length=50)),
                ('numero_motor', models.CharField(default='Desconocido', max_length=100)),
                ('imagen_base64', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleTransmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalle_transmision_registrados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_transmision', to='vehiculos.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRevisionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_generales_registradas', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_revision_general', to='vehiculos.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalle_motor_registrados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_motor', to='vehiculos.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_interior_registrados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_interior', to='vehiculos.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFrenos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalle_frenos_registrados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_frenos', to='vehiculos.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleDireccionSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalle_direccion_suspension_registrados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_direccion_suspension', to='vehiculos.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCarroceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalle_carroceria_registrados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_carroceria', to='vehiculos.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='PuntoCarroceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('estado_pintura', 'Estado de pintura'), ('abolladuras', 'Abolladuras o daños en carrocería'), ('estado_vidrios', 'Estado de vidrios'), ('alineacion_piezas', 'Alineación de piezas de carrocería')], max_length=50)),
                ('estado', models.CharField(choices=[('BUENO', 'Bueno'), ('REVISION', 'En Revisión'), ('RECHAZADO', 'Rechazado')], default='REVISION', max_length=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('imagen_base64', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='vehiculos.detallecarroceria')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_carroceria_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('detalle', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='PuntoDireccionSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('amortiguadores', 'Amortiguadores en buen estado'), ('alineacion', 'Alineación'), ('balanceo', 'Balanceo'), ('ruidos_tren_delantero', 'Ruidos en tren delantero'), ('ruidos_tren_trasero', 'Ruidos en tren trasero')], max_length=50)),
                ('estado', models.CharField(choices=[('BUENO', 'Bueno'), ('REVISION', 'En Revisión'), ('RECHAZADO', 'Rechazado')], default='REVISION', max_length=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('imagen_base64', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='vehiculos.detalledireccionsuspension')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_direccion_suspension_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('detalle', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='PuntoFrenos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('frenado_correcto', 'Frenado correcto a distancia adecuada'), ('sonidos_frenar', 'Sonidos al momento de frenar'), ('olgura_freno_mano', 'Olgura de freno de mano')], max_length=30)),
                ('estado', models.CharField(choices=[('BUENO', 'Bueno'), ('REVISION', 'En Revisión'), ('RECHAZADO', 'Rechazado')], default='REVISION', max_length=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('imagen_base64', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='vehiculos.detallefrenos')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_frenos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('detalle', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='PuntoInterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('estado_tapiz_butacas', 'Estado de tapiz y butacas'), ('funcionamiento_radio', 'Funcionamiento de radio'), ('desgaste_plasticos', 'Desgaste de plásticos'), ('accesorios_electricos', 'Estado de accesorios eléctricos'), ('estado_maleta', 'Estado de maleta')], max_length=50)),
                ('estado', models.CharField(choices=[('BUENO', 'Bueno'), ('REVISION', 'En Revisión'), ('RECHAZADO', 'Rechazado')], default='REVISION', max_length=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('imagen_base64', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='vehiculos.detalleinterior')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_interior_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('detalle', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='PuntoMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ruidos', 'Presencia de ruidos anormales en motor'), ('fugas', 'Fugas presentes en motor'), ('respuesta', 'Respuesta del motor')], max_length=20)),
                ('estado', models.CharField(choices=[('BUENO', 'Bueno'), ('REVISION', 'En Revisión'), ('RECHAZADO', 'Rechazado')], default='REVISION', max_length=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('imagen_base64', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='vehiculos.detallemotor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_motor_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('detalle', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='PuntoRevisionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('estado_luces', 'Estado de luces'), ('nivel_liquidos', 'Nivel de líquidos'), ('kit_emergencia', 'Existencia de kit de emergencia'), ('bateria_alternador', 'Estado de batería y alternador'), ('presencia_dtc', 'Presencia de DTC'), ('estado_ruedas', 'Estado de rueda y profundidad'), ('rueda_repuesto', 'Rueda de repuesto')], max_length=50)),
                ('estado', models.CharField(choices=[('BUENO', 'Bueno'), ('REVISION', 'En Revisión'), ('RECHAZADO', 'Rechazado')], default='REVISION', max_length=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('imagen_base64', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='vehiculos.detallerevisiongeneral')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_revision_general_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('detalle', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='PuntoTransmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('paso_marchas', 'Paso de marchas'), ('fugas_caja', 'Fugas presentes en caja'), ('estado_embrague', 'Estado de embrague')], max_length=30)),
                ('estado', models.CharField(choices=[('BUENO', 'Bueno'), ('REVISION', 'En Revisión'), ('RECHAZADO', 'Rechazado')], default='REVISION', max_length=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('imagen_base64', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='vehiculos.detalletransmision')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_transmision_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('detalle', 'nombre')},
            },
        ),
    ]
