# Generated by Django 5.2.3 on 2025-09-30 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntomotor',
            name='imagen_base64',
        ),
        migrations.CreateModel(
            name='PuntoMotorImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_base64', models.TextField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='vehiculos.puntomotor')),
            ],
        ),
    ]
