# Generated by Django 5.2.3 on 2025-09-30 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_remove_puntomotor_imagen_base64_puntomotorimagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntocarroceria',
            name='imagen_base64',
        ),
        migrations.RemoveField(
            model_name='puntodireccionsuspension',
            name='imagen_base64',
        ),
        migrations.RemoveField(
            model_name='puntofrenos',
            name='imagen_base64',
        ),
        migrations.RemoveField(
            model_name='puntointerior',
            name='imagen_base64',
        ),
        migrations.RemoveField(
            model_name='puntorevisiongeneral',
            name='imagen_base64',
        ),
        migrations.RemoveField(
            model_name='puntotransmision',
            name='imagen_base64',
        ),
        migrations.AddField(
            model_name='puntomotorimagen',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='puntocarroceria',
            name='estado',
            field=models.CharField(choices=[('BUENO', 'Bueno'), ('REVISION', 'En Revisión'), ('RECHAZADO', 'Rechazado')], default='REVISION', max_length=15),
        ),
        migrations.AlterField(
            model_name='puntodireccionsuspension',
            name='estado',
            field=models.CharField(choices=[('BUENO', 'Bueno'), ('REVISION', 'En Revisión'), ('RECHAZADO', 'Rechazado')], default='REVISION', max_length=15),
        ),
        migrations.AlterField(
            model_name='puntofrenos',
            name='estado',
            field=models.CharField(choices=[('BUENO', 'Bueno'), ('REVISION', 'En Revisión'), ('RECHAZADO', 'Rechazado')], default='REVISION', max_length=15),
        ),
        migrations.AlterField(
            model_name='puntointerior',
            name='estado',
            field=models.CharField(choices=[('BUENO', 'Bueno'), ('REVISION', 'En Revisión'), ('RECHAZADO', 'Rechazado')], default='REVISION', max_length=15),
        ),
        migrations.AlterField(
            model_name='puntomotor',
            name='estado',
            field=models.CharField(choices=[('BUENO', 'Bueno'), ('REVISION', 'En Revisión'), ('RECHAZADO', 'Rechazado')], default='REVISION', max_length=15),
        ),
        migrations.AlterField(
            model_name='puntorevisiongeneral',
            name='estado',
            field=models.CharField(choices=[('BUENO', 'Bueno'), ('REVISION', 'En Revisión'), ('RECHAZADO', 'Rechazado')], default='REVISION', max_length=15),
        ),
        migrations.AlterField(
            model_name='puntotransmision',
            name='estado',
            field=models.CharField(choices=[('BUENO', 'Bueno'), ('REVISION', 'En Revisión'), ('RECHAZADO', 'Rechazado')], default='REVISION', max_length=15),
        ),
        migrations.CreateModel(
            name='PuntoCarroceriaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_base64', models.TextField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='vehiculos.puntocarroceria')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PuntoDireccionSuspensionImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_base64', models.TextField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='vehiculos.puntodireccionsuspension')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PuntoFrenosImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_base64', models.TextField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='vehiculos.puntofrenos')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PuntoInteriorImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_base64', models.TextField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='vehiculos.puntointerior')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PuntoRevisionGeneralImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_base64', models.TextField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='vehiculos.puntorevisiongeneral')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PuntoTransmisionImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_base64', models.TextField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='vehiculos.puntotransmision')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
