# Generated by Django 5.2.3 on 2025-09-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_remove_puntocarroceria_imagen_base64_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntocarroceria',
            name='estado',
            field=models.CharField(choices=[('BUENO', 'Bueno'), ('OBSERVACION', 'Con Observación'), ('RECHAZADO', 'Rechazado')], default='REVISION', max_length=15),
        ),
        migrations.AlterField(
            model_name='puntodireccionsuspension',
            name='estado',
            field=models.CharField(choices=[('BUENO', 'Bueno'), ('OBSERVACION', 'Con Observación'), ('RECHAZADO', 'Rechazado')], default='REVISION', max_length=15),
        ),
        migrations.AlterField(
            model_name='puntofrenos',
            name='estado',
            field=models.CharField(choices=[('BUENO', 'Bueno'), ('OBSERVACION', 'Con Observación'), ('RECHAZADO', 'Rechazado')], default='REVISION', max_length=15),
        ),
        migrations.AlterField(
            model_name='puntointerior',
            name='estado',
            field=models.CharField(choices=[('BUENO', 'Bueno'), ('OBSERVACION', 'Con Observación'), ('RECHAZADO', 'Rechazado')], default='REVISION', max_length=15),
        ),
        migrations.AlterField(
            model_name='puntomotor',
            name='estado',
            field=models.CharField(choices=[('BUENO', 'Bueno'), ('OBSERVACION', 'Con Observación'), ('RECHAZADO', 'Rechazado')], default='REVISION', max_length=15),
        ),
        migrations.AlterField(
            model_name='puntorevisiongeneral',
            name='estado',
            field=models.CharField(choices=[('BUENO', 'Bueno'), ('OBSERVACION', 'Con Observación'), ('RECHAZADO', 'Rechazado')], default='REVISION', max_length=15),
        ),
        migrations.AlterField(
            model_name='puntotransmision',
            name='estado',
            field=models.CharField(choices=[('BUENO', 'Bueno'), ('OBSERVACION', 'Con Observación'), ('RECHAZADO', 'Rechazado')], default='REVISION', max_length=15),
        ),
    ]
